# This build is overkill for a POM-packaged artifact, but it serves as a test bed for some principles we'll use in
# child projects. Also, here's some documentation about Maven and GitHub publication:
#
# $ gpg --full-generate-key
# $ gpg --list-keys
# $ gpg --export-secret-keys [key ID] > travis.gpg
# $ gpg --keyserver pgp.mit.edu --send-key [key ID]
# $ tar -cvf .travis.secrets.tar settings.xml travis.gpg
# $ travis login --org
# $ travis encrypt-file .travis.secrets.tar
# $ rm .travis.secrets.tar settings.xml travis.gpg
# $ travis setup releases

language: java
sudo: false
cache:
  directories:
    - "$HOME/.cache"
jobs:
  include:
    - stage: build
      os: linux
      dist: trusty
      jdk: oraclejdk8
    - stage: build
      os: linux
      dist: trusty
      jdk: openjdk8
    - stage: build
      os: linux
      dist: xenial
      jdk: oraclejdk11
    - stage: build
      os: linux
      dist: xenial
      jdk: openjdk11
    - stage: deploy
      os: linux
      dist: xenial
      jdk: openjdk8
      before_deploy:
        # This is a workaround for travis-ci/dpl#673 and travis-ci/travis-yml#92, but it is not ideal because it runs
        # twice: once before each provider. As a result, we must first delete the secret key and ignore errors before
        # importing the secret key.
        - openssl aes-256-cbc -K $encrypted_dc2adf587a89_key -iv $encrypted_dc2adf587a89_iv -in .travis.secrets.tar.enc -out .travis.secrets.tar -d
        - tar -xvf .travis.secrets.tar
        - rm .travis.secrets.tar
        - gpg --batch --delete-secret-keys 5224F049F154E1FAA46C13C37B440CA3BEB1A41F || true
        - gpg --import travis.gpg
        - rm travis.gpg
        - mv settings.xml $HOME/.m2/settings.xml
      deploy:
        - provider: script
          script: "mvn clean deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -P sign -B -V -e"
          on:
            tags: true
          skip_cleanup: true
        - provider: releases
          api_key:
            secure: CKKEi9hoNjkMbXxrrCvRiY13ez1HtUMdce2RV8mGJOGrb0eZ4bi22oA/c9Z4jgCGxJCiJcP2AQHejHCAg38m9gj5qgBWyHAHumBrCkk7DeroltWxNsP21QGhZvSFKkTdTDzn/fnqT9aXRIcOistpJlKcUs0Tn0SLP1N+bI/t6pN6OK4zenGxZxademdDycBVP9P4JH7u80dFWzpJ2WXj2vF0DHhq5vnZLXp+ECsWlhtMjZHY17T/6fdPMYr5bvBAYUj3xen0iOYm3tmMYdJal3gjkeKAt/2PdP4OVn2tl65vYHOUb4fyrBsGw9KUc3u/QDsEILZhGrac18JY8g9CsQwRrRti+riUHBPopsTNgqBZ1EosmagZg9IdAagr6wxEEM4eVgObf5/U037SS287qTb8psXm4GN1buswIVn11YLKeRy7eK8PloHDXrG7vQ9EUVxVjzgNB333vdZDX76fo9sMAh4Kr/4Ag81iGPktVzyS8E396+wpaijZm4dut+C/RKI1nAzRme4E1y3nSsvAsR6aNpNmz3EZ/KrN0ExYCChev4YdRSlkn8IuMx8pJAYvHsOM50Xv/2OwPPd7Rg54MIA8W4bUzosVWwe3Co2vUj9BPoUK3E3eSr7Fmh6LjM6OUQeHN/G20QdBN8UIu6E5gmST8pQi/rkgxbzZByUU80Q=
          file_glob: true
          file:
            - $HOME/.m2/repository/io/oddsource/java/oss-parent/*/oss-parent-*.pom
            - $HOME/.m2/repository/io/oddsource/java/oss-parent/*/oss-parent-*.pom.asc
            - $HOME/.m2/repository/io/oddsource/java/oss-parent/*/oss-parent-*.pom.md5
            - $HOME/.m2/repository/io/oddsource/java/oss-parent/*/oss-parent-*.pom.sha1
          on:
            tags: true
stages:
  - build
  - name: deploy
    if: tag =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$
install:
  - gpg --version
  - mvn process-resources -B -V -e
script:
  - mvn test -B -V -e
